% Simple facts.

?- sibling(jolteon, X).
number(pikachu, 25).
evolves(pikachu, raichu).
evolves(charmander, charmeleon).
evolves(charmeleon, charizard).
evolves(eevee, jolteon).
evolves(eevee, flareon).
evolves(eevee, vaporeon).

% Slightly more complex facts.

move(thunderbolt, electric, special, 90).
move(thunderpunch, electric, physical, 75).
learns(pikachu, thunderbolt, level(36)). % Pikachu learns Thunderbolt at level 36.
learns(pikachu, thunderpunch, tm(5)).    % Pikachu learns Thunderpunch by using the item TM5.


% Simple rules.

sibling(X, Y) :- evolves(Parent, X), evolves(Parent, Y), X \= Y. % the comma means "and". "\=" means "does not unify".

canUseItem(Pokemon, tm(X)) :- learns(Pokemon, _, tm(X)). % _ is "don't care", yet again.


% A rule with multiple clauses.
descendent(X, Y) :- evolves(Y, X).
descendent(X, Y) :- evolves(Y, Z), descendent(X, Z). % This one is recursive!!




% Generated by ChatGPT; probably has some hallucinations.
% Weaknesses
% Implement: damageAmount(AttackType, DefenseType, Damage).
% Damage = 0.5 if DefenseType resists AttackType.
%        = 2.0 if DefenseType is weak to AttackType.
%        = 0.0 if DefenseType is immune to AttackType.

weak_to(grass, fire).
weak_to(grass, ice).
weak_to(grass, poison).
weak_to(grass, flying).
weak_to(grass, bug).

weak_to(fire, water).
weak_to(fire, rock).
weak_to(fire, ground).

weak_to(water, electric).
weak_to(water, grass).

weak_to(electric, ground).

weak_to(ice, fire).
weak_to(ice, rock).
weak_to(ice, steel).
weak_to(ice, fighting).

weak_to(fighting, flying).
weak_to(fighting, psychic).
weak_to(fighting, fairy).

weak_to(poison, ground).
weak_to(poison, psychic).

weak_to(ground, water).
weak_to(ground, ice).
weak_to(ground, grass).

weak_to(flying, rock).
weak_to(flying, electric).
weak_to(flying, ice).

weak_to(psychic, bug).
weak_to(psychic, ghost).
weak_to(psychic, dark).

weak_to(bug, fire).
weak_to(bug, flying).
weak_to(bug, rock).

weak_to(rock, water).
weak_to(rock, grass).
weak_to(rock, fighting).
weak_to(rock, ground).
weak_to(rock, steel).

weak_to(ghost, ghost).
weak_to(ghost, dark).

weak_to(dragon, ice).
weak_to(dragon, dragon).
weak_to(dragon, fairy).

weak_to(dark, fighting).
weak_to(dark, bug).
weak_to(dark, fairy).

weak_to(steel, fire).
weak_to(steel, fighting).
weak_to(steel, ground).

weak_to(fairy, poison).
weak_to(fairy, steel).

% Resistances
resists(grass, water).
resists(grass, electric).
resists(grass, ground).

resists(fire, fire).
resists(fire, grass).
resists(fire, bug).
resists(fire, ice).
resists(fire, steel).

resists(water, fire).
resists(water, water).
resists(water, ice).
resists(water, steel).

resists(electric, electric).
resists(electric, flying).
resists(electric, steel).

resists(ice, ice).

resists(fighting, rock).
resists(fighting, bug).
resists(fighting, dark).

resists(poison, grass).
resists(poison, fighting).
resists(poison, poison).
resists(poison, bug).
resists(poison, fairy).

resists(ground, poison).
resists(ground, rock).

resists(flying, grass).
resists(flying, fighting).
resists(flying, bug).

resists(psychic, fighting).
resists(psychic, psychic).

resists(bug, grass).
resists(bug, fighting).
resists(bug, ground).

resists(rock, normal).
resists(rock, fire).
resists(rock, poison).
resists(rock, flying).

resists(ghost, poison).
resists(ghost, bug).

resists(dragon, fire).
resists(dragon, water).
resists(dragon, grass).
resists(dragon, electric).

resists(dark, ghost).
resists(dark, dark).

resists(steel, normal).
resists(steel, grass).
resists(steel, ice).
resists(steel, flying).
resists(steel, psychic).
resists(steel, bug).
resists(steel, rock).
resists(steel, dragon).
resists(steel, fairy).

resists(fairy, fighting).
resists(fairy, bug).
resists(fairy, dark).

% Immunities
immune_to(ground, electric).
immune_to(normal, ghost).
immune_to(ghost, normal).
immune_to(ghost, fighting).
immune_to(dragon, fairy).
immune_to(psychic, dark).
immune_to(flying, ground).
immune_to(steel, poison).
